name: smallantimagmas
version: "0.1.1"
license: "MIT"
date: 2024-08-27
description: |
    A fork of smallgrp package for small antiassociative magmas

authors:
    - name: Kamil Zabielski

maintainers:
    - name: Kamil Zabielski

GAP: "4.12"

needed-pkgs:
    - name: "GAPDoc"
      version: "1.5"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://github.com/limakzi/smallantimagmas
readme: README.md
packageinfo: https://github.com/limakzi/smallantimagmas/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/limakzi/smallantimagmas/archive/refs/tags/v0.1.1/smallantimagmas-0.1.1.tar.gz

abstract: |
    The <span class="pkgname">smallantimagmas</span> package,            is an example of how to create a <span class="pkgname">GAP</span>    package. It has little functionality except for being a package.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    smallantimagmas, antiassociative.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Zab24</span>]   <b class='BibAuthor'>Zabielski, K.</b>,
     <i class='BibTitle'>smallantimagmas, A fork of smallgrp package for small antiassociative magmas,
             Version 0.1.1</i>
     (<span class='BibYear'>2024</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://github.com/limakzi/smallantimagmas">https://github.com/limakzi/smallantimagmas</a></span>.
    </p>
    

bibtex: |
    @misc{ smallantimagmas,
      author =           {Zabielski, K.},
      title =            {{smallantimagmas},  A  fork  of  smallgrp  package for
                          small antiassociative magmas, {V}ersion 0.1.1},
      month =            {Aug},
      year =             {2024},
      note =             {GAP package},
      howpublished =     {\href     {https://github.com/limakzi/smallantimagmas}
                          {\texttt{https://github.com/}\discretionary
                          {}{}{}\texttt{limakzi/}\discretionary
                          {}{}{}\texttt{smallantimagmas}}},
      keywords =         {smallantimagmas; antiassociative},
      printedkey =       {Zab24}
    }

